version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      target: dev
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

networks:
  webnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'true'
      com.docker.network.bridge.host_binding_ipv4: 0.0.0.0
volumes:
  pgdata:
