FROM golang:1.14-alpine AS build

WORKDIR /src/
COPY hello.go /src/
RUN CGO_ENABLED=0 go build -ldflags "-s -w" -o /bin/demo

FROM scratch

COPY --from=build /bin/demo /bin/demo
ENTRYPOINT ["/bin/demo"]
